#%RAML 1.0 Overlay
extends: craft-online-shopping.raml
title: translation 
documentation:
  - title: translation
    content: this RAML endpoints are translated to Spansh
     /producto
     /usuarias
     /orden
     /categoria




  

